version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - attach_workspace:
          at: .
      - run: |
          aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
          aws s3 sync ./build s3://BUCKET_NAME --delete
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
